name: sitemap

on:
  schedule:
    - cron: '0 0 * * *'
  push

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - name: Run sitemap ping script
        run: node scripts/ping-sitemap.js
